//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Customer
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Customer :
        global::LightSwitchApplication.Customer.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCustomerNameChanged()
        {
            this.___OnPropertyChanged("CustomerName");
        }
        
        partial void OnAddressChanged()
        {
            this.___OnPropertyChanged("Address");
        }
        
        partial void OnCityChanged()
        {
            this.___OnPropertyChanged("City");
        }
        
        partial void OnStateChanged()
        {
            this.___OnPropertyChanged("State");
        }
        
        partial void OnCountryChanged()
        {
            this.___OnPropertyChanged("Country");
        }
        
        partial void OnPostCodeChanged()
        {
            this.___OnPropertyChanged("PostCode");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnPhone1Changed()
        {
            this.___OnPropertyChanged("Phone1");
        }
        
        partial void OnPhone2Changed()
        {
            this.___OnPropertyChanged("Phone2");
        }
        
        partial void OnFaxChanged()
        {
            this.___OnPropertyChanged("Fax");
        }
        
        partial void OnWebsiteChanged()
        {
            this.___OnPropertyChanged("Website");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Customer.DetailsClass.IImplementation.Orders
        {
            get
            {
                return this.Orders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> __Orders
        {
            get
            {
                if (this.___Orders == null)
                {
                    this.___Orders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order>(
                        this,
                        "Orders",
                        () => this._Orders,
                        e => global::System.Object.Equals(e.Customer_Order, this.Id));
                }
                return this.___Orders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> ___Orders;
        
    }
    #endregion
    
    #region Employee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnCurrentChanged()
        {
            this.___OnPropertyChanged("Current");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.Orders
        {
            get
            {
                return this.Orders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> __Orders
        {
            get
            {
                if (this.___Orders == null)
                {
                    this.___Orders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order>(
                        this,
                        "Orders",
                        () => this._Orders,
                        e => global::System.Object.Equals(e.Order_Employee, this.Id));
                }
                return this.___Orders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> ___Orders;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.StockChecks
        {
            get
            {
                return this.StockChecks;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.StockCheck> __StockChecks
        {
            get
            {
                if (this.___StockChecks == null)
                {
                    this.___StockChecks = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.StockCheck>(
                        this,
                        "StockChecks",
                        () => this._StockChecks,
                        e => global::System.Object.Equals(e.StockCheck_Employee, this.Id));
                }
                return this.___StockChecks;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.StockCheck> ___StockChecks;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ProductSubscribers
        {
            get
            {
                return this.ProductSubscribers;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductSubscriber> __ProductSubscribers
        {
            get
            {
                if (this.___ProductSubscribers == null)
                {
                    this.___ProductSubscribers = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductSubscriber>(
                        this,
                        "ProductSubscribers",
                        () => this._ProductSubscribers,
                        e => global::System.Object.Equals(e.ProductSubscriber_Employee, this.Id));
                }
                return this.___ProductSubscribers;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductSubscriber> ___ProductSubscribers;
        
    }
    #endregion
    
    #region OrderDetail
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class OrderDetail :
        global::LightSwitchApplication.OrderDetail.DetailsClass.IImplementation
    {
        partial void OnOrderDetail_OrderChanged()
        {
            this.___OnPropertyChanged("OrderDetail_Order");
            this.___OnPropertyChanged("Order");
        }
        
        partial void OnOrderDetail_ProductChanged()
        {
            this.___OnPropertyChanged("OrderDetail_Product");
            this.___OnPropertyChanged("Product");
        }
        
        partial void OnOrderDetail_ShippingMethodChanged()
        {
            this.___OnPropertyChanged("OrderDetail_ShippingMethod");
            this.___OnPropertyChanged("ShippingMethod");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnUnitsOrderedChanged()
        {
            this.___OnPropertyChanged("UnitsOrdered");
        }
        
        partial void OnUnitsShippedChanged()
        {
            this.___OnPropertyChanged("UnitsShipped");
        }
        
        partial void OnDateOrderShippedChanged()
        {
            this.___OnPropertyChanged("DateOrderShipped");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.OrderDetail.DetailsClass.IImplementation.Order
        {
            get
            {
                return this.Order;
            }
            set
            {
                this.Order = (global::LightSwitchApplication.Implementation.Order)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Order> __Order
        {
            get
            {
                if (this.___Order == null)
                {
                    this.___Order = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Order>(
                        this,
                        "Order",
                        new string[] { "OrderDetail_Order" },
                        e => global::System.Object.Equals(e.Id, this.OrderDetail_Order),
                        () => this._Order,
                        e => this._Order = e);
                }
                return this.___Order;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Order> ___Order;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.OrderDetail.DetailsClass.IImplementation.Product
        {
            get
            {
                return this.Product;
            }
            set
            {
                this.Product = (global::LightSwitchApplication.Implementation.Product)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product> __Product
        {
            get
            {
                if (this.___Product == null)
                {
                    this.___Product = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product>(
                        this,
                        "Product",
                        new string[] { "OrderDetail_Product" },
                        e => global::System.Object.Equals(e.Id, this.OrderDetail_Product),
                        () => this._Product,
                        e => this._Product = e);
                }
                return this.___Product;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product> ___Product;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.OrderDetail.DetailsClass.IImplementation.ShippingMethod
        {
            get
            {
                return this.ShippingMethod;
            }
            set
            {
                this.ShippingMethod = (global::LightSwitchApplication.Implementation.ShippingMethod)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ShippingMethod> __ShippingMethod
        {
            get
            {
                if (this.___ShippingMethod == null)
                {
                    this.___ShippingMethod = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ShippingMethod>(
                        this,
                        "ShippingMethod",
                        new string[] { "OrderDetail_ShippingMethod" },
                        e => global::System.Object.Equals(e.Id, this.OrderDetail_ShippingMethod),
                        () => this._ShippingMethod,
                        e => this._ShippingMethod = e);
                }
                return this.___ShippingMethod;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ShippingMethod> ___ShippingMethod;
        
    }
    #endregion
    
    #region Order
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Order :
        global::LightSwitchApplication.Order.DetailsClass.IImplementation
    {
        partial void OnCustomer_OrderChanged()
        {
            this.___OnPropertyChanged("Customer_Order");
            this.___OnPropertyChanged("Customer");
        }
        
        partial void OnOrder_EmployeeChanged()
        {
            this.___OnPropertyChanged("Order_Employee");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnOrderReferenceChanged()
        {
            this.___OnPropertyChanged("OrderReference");
        }
        
        partial void OnOrderDateChanged()
        {
            this.___OnPropertyChanged("OrderDate");
        }
        
        partial void OnOrderPaidForChanged()
        {
            this.___OnPropertyChanged("OrderPaidFor");
        }
        
        partial void OnDatePaidChanged()
        {
            this.___OnPropertyChanged("DatePaid");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.Customer
        {
            get
            {
                return this.Customer;
            }
            set
            {
                this.Customer = (global::LightSwitchApplication.Implementation.Customer)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer> __Customer
        {
            get
            {
                if (this.___Customer == null)
                {
                    this.___Customer = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer>(
                        this,
                        "Customer",
                        new string[] { "Customer_Order" },
                        e => global::System.Object.Equals(e.Id, this.Customer_Order),
                        () => this._Customer,
                        e => this._Customer = e);
                }
                return this.___Customer;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer> ___Customer;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "Order_Employee" },
                        e => global::System.Object.Equals(e.Id, this.Order_Employee),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Order.DetailsClass.IImplementation.OrderDetails
        {
            get
            {
                return this.OrderDetails;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderDetail> __OrderDetails
        {
            get
            {
                if (this.___OrderDetails == null)
                {
                    this.___OrderDetails = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderDetail>(
                        this,
                        "OrderDetails",
                        () => this._OrderDetails,
                        e => global::System.Object.Equals(e.OrderDetail_Order, this.Id));
                }
                return this.___OrderDetails;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderDetail> ___OrderDetails;
        
    }
    #endregion
    
    #region ProductCategory
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProductCategory :
        global::LightSwitchApplication.ProductCategory.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCategoryChanged()
        {
            this.___OnPropertyChanged("Category");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProductCategory.DetailsClass.IImplementation.Products
        {
            get
            {
                return this.Products;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Product> __Products
        {
            get
            {
                if (this.___Products == null)
                {
                    this.___Products = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Product>(
                        this,
                        "Products",
                        () => this._Products,
                        e => global::System.Object.Equals(e.ProductCategory_Product, this.Id));
                }
                return this.___Products;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Product> ___Products;
        
    }
    #endregion
    
    #region Product
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Product :
        global::LightSwitchApplication.Product.DetailsClass.IImplementation
    {
        partial void OnProductCategory_ProductChanged()
        {
            this.___OnPropertyChanged("ProductCategory_Product");
            this.___OnPropertyChanged("ProductCategory");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnProductNameChanged()
        {
            this.___OnPropertyChanged("ProductName");
        }
        
        partial void OnProductDescriptionChanged()
        {
            this.___OnPropertyChanged("ProductDescription");
        }
        
        partial void OnUnitPriceChanged()
        {
            this.___OnPropertyChanged("UnitPrice");
        }
        
        partial void OnReorderLevelChanged()
        {
            this.___OnPropertyChanged("ReorderLevel");
        }
        
        partial void OnDiscontinuedChanged()
        {
            this.___OnPropertyChanged("Discontinued");
        }
        
        partial void OnLeadTimeChanged()
        {
            this.___OnPropertyChanged("LeadTime");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Product.DetailsClass.IImplementation.ProductCategory
        {
            get
            {
                return this.ProductCategory;
            }
            set
            {
                this.ProductCategory = (global::LightSwitchApplication.Implementation.ProductCategory)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductCategory> __ProductCategory
        {
            get
            {
                if (this.___ProductCategory == null)
                {
                    this.___ProductCategory = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductCategory>(
                        this,
                        "ProductCategory",
                        new string[] { "ProductCategory_Product" },
                        e => global::System.Object.Equals(e.Id, this.ProductCategory_Product),
                        () => this._ProductCategory,
                        e => this._ProductCategory = e);
                }
                return this.___ProductCategory;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductCategory> ___ProductCategory;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Product.DetailsClass.IImplementation.OrderDetails
        {
            get
            {
                return this.OrderDetails;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderDetail> __OrderDetails
        {
            get
            {
                if (this.___OrderDetails == null)
                {
                    this.___OrderDetails = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderDetail>(
                        this,
                        "OrderDetails",
                        () => this._OrderDetails,
                        e => global::System.Object.Equals(e.OrderDetail_Product, this.Id));
                }
                return this.___OrderDetails;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderDetail> ___OrderDetails;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Product.DetailsClass.IImplementation.PurchaseOrderDetails
        {
            get
            {
                return this.PurchaseOrderDetails;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrderDetail> __PurchaseOrderDetails
        {
            get
            {
                if (this.___PurchaseOrderDetails == null)
                {
                    this.___PurchaseOrderDetails = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrderDetail>(
                        this,
                        "PurchaseOrderDetails",
                        () => this._PurchaseOrderDetails,
                        e => global::System.Object.Equals(e.PurchaseOrderDetails_Product, this.Id));
                }
                return this.___PurchaseOrderDetails;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrderDetail> ___PurchaseOrderDetails;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Product.DetailsClass.IImplementation.StockCheckDetails
        {
            get
            {
                return this.StockCheckDetails;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.StockCheckDetail> __StockCheckDetails
        {
            get
            {
                if (this.___StockCheckDetails == null)
                {
                    this.___StockCheckDetails = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.StockCheckDetail>(
                        this,
                        "StockCheckDetails",
                        () => this._StockCheckDetails,
                        e => global::System.Object.Equals(e.Shrinkage_Product, this.Id));
                }
                return this.___StockCheckDetails;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.StockCheckDetail> ___StockCheckDetails;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Product.DetailsClass.IImplementation.ProductSubscribers
        {
            get
            {
                return this.ProductSubscribers;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductSubscriber> __ProductSubscribers
        {
            get
            {
                if (this.___ProductSubscribers == null)
                {
                    this.___ProductSubscribers = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductSubscriber>(
                        this,
                        "ProductSubscribers",
                        () => this._ProductSubscribers,
                        e => global::System.Object.Equals(e.ProductSubscriber_Product, this.Id));
                }
                return this.___ProductSubscribers;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductSubscriber> ___ProductSubscribers;
        
    }
    #endregion
    
    #region ProductSubscriber
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProductSubscriber :
        global::LightSwitchApplication.ProductSubscriber.DetailsClass.IImplementation
    {
        partial void OnProductSubscriber_ProductChanged()
        {
            this.___OnPropertyChanged("ProductSubscriber_Product");
            this.___OnPropertyChanged("Product");
        }
        
        partial void OnProductSubscriber_EmployeeChanged()
        {
            this.___OnPropertyChanged("ProductSubscriber_Employee");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProductSubscriber.DetailsClass.IImplementation.Product
        {
            get
            {
                return this.Product;
            }
            set
            {
                this.Product = (global::LightSwitchApplication.Implementation.Product)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product> __Product
        {
            get
            {
                if (this.___Product == null)
                {
                    this.___Product = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product>(
                        this,
                        "Product",
                        new string[] { "ProductSubscriber_Product" },
                        e => global::System.Object.Equals(e.Id, this.ProductSubscriber_Product),
                        () => this._Product,
                        e => this._Product = e);
                }
                return this.___Product;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product> ___Product;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProductSubscriber.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "ProductSubscriber_Employee" },
                        e => global::System.Object.Equals(e.Id, this.ProductSubscriber_Employee),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
    }
    #endregion
    
    #region PurchaseOrderDetail
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class PurchaseOrderDetail :
        global::LightSwitchApplication.PurchaseOrderDetail.DetailsClass.IImplementation
    {
        partial void OnPurchaseOrderDetails_PurchaseOrderChanged()
        {
            this.___OnPropertyChanged("PurchaseOrderDetails_PurchaseOrder");
            this.___OnPropertyChanged("PurchaseOrder");
        }
        
        partial void OnPurchaseOrderDetails_ProductChanged()
        {
            this.___OnPropertyChanged("PurchaseOrderDetails_Product");
            this.___OnPropertyChanged("Product");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnUnitsOrderedChanged()
        {
            this.___OnPropertyChanged("UnitsOrdered");
        }
        
        partial void OnDiscountChanged()
        {
            this.___OnPropertyChanged("Discount");
        }
        
        partial void OnUnitPricePaidChanged()
        {
            this.___OnPropertyChanged("UnitPricePaid");
        }
        
        partial void OnUnitsReceivedChanged()
        {
            this.___OnPropertyChanged("UnitsReceived");
        }
        
        partial void OnDateRecievedChanged()
        {
            this.___OnPropertyChanged("DateRecieved");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.PurchaseOrderDetail.DetailsClass.IImplementation.PurchaseOrder
        {
            get
            {
                return this.PurchaseOrder;
            }
            set
            {
                this.PurchaseOrder = (global::LightSwitchApplication.Implementation.PurchaseOrder)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PurchaseOrder> __PurchaseOrder
        {
            get
            {
                if (this.___PurchaseOrder == null)
                {
                    this.___PurchaseOrder = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PurchaseOrder>(
                        this,
                        "PurchaseOrder",
                        new string[] { "PurchaseOrderDetails_PurchaseOrder" },
                        e => global::System.Object.Equals(e.Id, this.PurchaseOrderDetails_PurchaseOrder),
                        () => this._PurchaseOrder,
                        e => this._PurchaseOrder = e);
                }
                return this.___PurchaseOrder;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PurchaseOrder> ___PurchaseOrder;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.PurchaseOrderDetail.DetailsClass.IImplementation.Product
        {
            get
            {
                return this.Product;
            }
            set
            {
                this.Product = (global::LightSwitchApplication.Implementation.Product)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product> __Product
        {
            get
            {
                if (this.___Product == null)
                {
                    this.___Product = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product>(
                        this,
                        "Product",
                        new string[] { "PurchaseOrderDetails_Product" },
                        e => global::System.Object.Equals(e.Id, this.PurchaseOrderDetails_Product),
                        () => this._Product,
                        e => this._Product = e);
                }
                return this.___Product;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product> ___Product;
        
    }
    #endregion
    
    #region PurchaseOrder
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class PurchaseOrder :
        global::LightSwitchApplication.PurchaseOrder.DetailsClass.IImplementation
    {
        partial void OnPurchaseOrder_SupplierChanged()
        {
            this.___OnPropertyChanged("PurchaseOrder_Supplier");
            this.___OnPropertyChanged("Supplier");
        }
        
        partial void OnPurchaseOrder_ShippingMethodChanged()
        {
            this.___OnPropertyChanged("PurchaseOrder_ShippingMethod");
            this.___OnPropertyChanged("ShippingMethod");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnPurchaseOrderNumberChanged()
        {
            this.___OnPropertyChanged("PurchaseOrderNumber");
        }
        
        partial void OnPurchaseOrderDescriptionChanged()
        {
            this.___OnPropertyChanged("PurchaseOrderDescription");
        }
        
        partial void OnDatePurchaseOrderPlacedChanged()
        {
            this.___OnPropertyChanged("DatePurchaseOrderPlaced");
        }
        
        partial void OnDatePurchaseOrderRequiredChanged()
        {
            this.___OnPropertyChanged("DatePurchaseOrderRequired");
        }
        
        partial void OnDatePurchaseOrderShippedChanged()
        {
            this.___OnPropertyChanged("DatePurchaseOrderShipped");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.PurchaseOrder.DetailsClass.IImplementation.Supplier
        {
            get
            {
                return this.Supplier;
            }
            set
            {
                this.Supplier = (global::LightSwitchApplication.Implementation.Supplier)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Supplier> __Supplier
        {
            get
            {
                if (this.___Supplier == null)
                {
                    this.___Supplier = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Supplier>(
                        this,
                        "Supplier",
                        new string[] { "PurchaseOrder_Supplier" },
                        e => global::System.Object.Equals(e.Id, this.PurchaseOrder_Supplier),
                        () => this._Supplier,
                        e => this._Supplier = e);
                }
                return this.___Supplier;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Supplier> ___Supplier;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.PurchaseOrder.DetailsClass.IImplementation.ShippingMethod
        {
            get
            {
                return this.ShippingMethod;
            }
            set
            {
                this.ShippingMethod = (global::LightSwitchApplication.Implementation.ShippingMethod)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ShippingMethod> __ShippingMethod
        {
            get
            {
                if (this.___ShippingMethod == null)
                {
                    this.___ShippingMethod = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ShippingMethod>(
                        this,
                        "ShippingMethod",
                        new string[] { "PurchaseOrder_ShippingMethod" },
                        e => global::System.Object.Equals(e.Id, this.PurchaseOrder_ShippingMethod),
                        () => this._ShippingMethod,
                        e => this._ShippingMethod = e);
                }
                return this.___ShippingMethod;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ShippingMethod> ___ShippingMethod;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.PurchaseOrder.DetailsClass.IImplementation.PurchaseOrderDetailsCollection
        {
            get
            {
                return this.PurchaseOrderDetailsCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrderDetail> __PurchaseOrderDetailsCollection
        {
            get
            {
                if (this.___PurchaseOrderDetailsCollection == null)
                {
                    this.___PurchaseOrderDetailsCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrderDetail>(
                        this,
                        "PurchaseOrderDetailsCollection",
                        () => this._PurchaseOrderDetailsCollection,
                        e => global::System.Object.Equals(e.PurchaseOrderDetails_PurchaseOrder, this.Id));
                }
                return this.___PurchaseOrderDetailsCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrderDetail> ___PurchaseOrderDetailsCollection;
        
    }
    #endregion
    
    #region ShippingMethod
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ShippingMethod :
        global::LightSwitchApplication.ShippingMethod.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnShipperChanged()
        {
            this.___OnPropertyChanged("Shipper");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ShippingMethod.DetailsClass.IImplementation.PurchaseOrders
        {
            get
            {
                return this.PurchaseOrders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrder> __PurchaseOrders
        {
            get
            {
                if (this.___PurchaseOrders == null)
                {
                    this.___PurchaseOrders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrder>(
                        this,
                        "PurchaseOrders",
                        () => this._PurchaseOrders,
                        e => global::System.Object.Equals(e.PurchaseOrder_ShippingMethod, this.Id));
                }
                return this.___PurchaseOrders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrder> ___PurchaseOrders;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ShippingMethod.DetailsClass.IImplementation.OrderDetails
        {
            get
            {
                return this.OrderDetails;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderDetail> __OrderDetails
        {
            get
            {
                if (this.___OrderDetails == null)
                {
                    this.___OrderDetails = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderDetail>(
                        this,
                        "OrderDetails",
                        () => this._OrderDetails,
                        e => global::System.Object.Equals(e.OrderDetail_ShippingMethod, this.Id));
                }
                return this.___OrderDetails;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderDetail> ___OrderDetails;
        
    }
    #endregion
    
    #region StockCheckDetail
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class StockCheckDetail :
        global::LightSwitchApplication.StockCheckDetail.DetailsClass.IImplementation
    {
        partial void OnStockCheckDetails_StockCheckChanged()
        {
            this.___OnPropertyChanged("StockCheckDetails_StockCheck");
            this.___OnPropertyChanged("StockCheck");
        }
        
        partial void OnShrinkage_ProductChanged()
        {
            this.___OnPropertyChanged("Shrinkage_Product");
            this.___OnPropertyChanged("Product");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnUnitsExpectedChanged()
        {
            this.___OnPropertyChanged("UnitsExpected");
        }
        
        partial void OnUnitsFoundChanged()
        {
            this.___OnPropertyChanged("UnitsFound");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.StockCheckDetail.DetailsClass.IImplementation.StockCheck
        {
            get
            {
                return this.StockCheck;
            }
            set
            {
                this.StockCheck = (global::LightSwitchApplication.Implementation.StockCheck)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.StockCheck> __StockCheck
        {
            get
            {
                if (this.___StockCheck == null)
                {
                    this.___StockCheck = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.StockCheck>(
                        this,
                        "StockCheck",
                        new string[] { "StockCheckDetails_StockCheck" },
                        e => global::System.Object.Equals(e.Id, this.StockCheckDetails_StockCheck),
                        () => this._StockCheck,
                        e => this._StockCheck = e);
                }
                return this.___StockCheck;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.StockCheck> ___StockCheck;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.StockCheckDetail.DetailsClass.IImplementation.Product
        {
            get
            {
                return this.Product;
            }
            set
            {
                this.Product = (global::LightSwitchApplication.Implementation.Product)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product> __Product
        {
            get
            {
                if (this.___Product == null)
                {
                    this.___Product = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product>(
                        this,
                        "Product",
                        new string[] { "Shrinkage_Product" },
                        e => global::System.Object.Equals(e.Id, this.Shrinkage_Product),
                        () => this._Product,
                        e => this._Product = e);
                }
                return this.___Product;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product> ___Product;
        
    }
    #endregion
    
    #region StockCheck
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class StockCheck :
        global::LightSwitchApplication.StockCheck.DetailsClass.IImplementation
    {
        partial void OnStockCheck_EmployeeChanged()
        {
            this.___OnPropertyChanged("StockCheck_Employee");
            this.___OnPropertyChanged("StockCheckBy");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnStockCheckDateChanged()
        {
            this.___OnPropertyChanged("StockCheckDate");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.StockCheck.DetailsClass.IImplementation.StockCheckBy
        {
            get
            {
                return this.StockCheckBy;
            }
            set
            {
                this.StockCheckBy = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __StockCheckBy
        {
            get
            {
                if (this.___StockCheckBy == null)
                {
                    this.___StockCheckBy = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "StockCheckBy",
                        new string[] { "StockCheck_Employee" },
                        e => global::System.Object.Equals(e.Id, this.StockCheck_Employee),
                        () => this._StockCheckBy,
                        e => this._StockCheckBy = e);
                }
                return this.___StockCheckBy;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___StockCheckBy;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.StockCheck.DetailsClass.IImplementation.StockCheckDetails
        {
            get
            {
                return this.StockCheckDetails;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.StockCheckDetail> __StockCheckDetails
        {
            get
            {
                if (this.___StockCheckDetails == null)
                {
                    this.___StockCheckDetails = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.StockCheckDetail>(
                        this,
                        "StockCheckDetails",
                        () => this._StockCheckDetails,
                        e => global::System.Object.Equals(e.StockCheckDetails_StockCheck, this.Id));
                }
                return this.___StockCheckDetails;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.StockCheckDetail> ___StockCheckDetails;
        
    }
    #endregion
    
    #region Supplier
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Supplier :
        global::LightSwitchApplication.Supplier.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnSupplierNameChanged()
        {
            this.___OnPropertyChanged("SupplierName");
        }
        
        partial void OnAddressChanged()
        {
            this.___OnPropertyChanged("Address");
        }
        
        partial void OnCityChanged()
        {
            this.___OnPropertyChanged("City");
        }
        
        partial void OnStateChanged()
        {
            this.___OnPropertyChanged("State");
        }
        
        partial void OnCountryChanged()
        {
            this.___OnPropertyChanged("Country");
        }
        
        partial void OnPostCodeChanged()
        {
            this.___OnPropertyChanged("PostCode");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnPhone1Changed()
        {
            this.___OnPropertyChanged("Phone1");
        }
        
        partial void OnPhone2Changed()
        {
            this.___OnPropertyChanged("Phone2");
        }
        
        partial void OnFaxChanged()
        {
            this.___OnPropertyChanged("Fax");
        }
        
        partial void OnWebsiteChanged()
        {
            this.___OnPropertyChanged("Website");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Supplier.DetailsClass.IImplementation.PurchaseOrders
        {
            get
            {
                return this.PurchaseOrders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrder> __PurchaseOrders
        {
            get
            {
                if (this.___PurchaseOrders == null)
                {
                    this.___PurchaseOrders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrder>(
                        this,
                        "PurchaseOrders",
                        () => this._PurchaseOrders,
                        e => global::System.Object.Equals(e.PurchaseOrder_Supplier, this.Id));
                }
                return this.___PurchaseOrders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PurchaseOrder> ___PurchaseOrders;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Customer))
            {
                return new global::LightSwitchApplication.Implementation.Customer();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.OrderDetail))
            {
                return new global::LightSwitchApplication.Implementation.OrderDetail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Order))
            {
                return new global::LightSwitchApplication.Implementation.Order();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProductCategory))
            {
                return new global::LightSwitchApplication.Implementation.ProductCategory();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Product))
            {
                return new global::LightSwitchApplication.Implementation.Product();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProductSubscriber))
            {
                return new global::LightSwitchApplication.Implementation.ProductSubscriber();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.PurchaseOrderDetail))
            {
                return new global::LightSwitchApplication.Implementation.PurchaseOrderDetail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.PurchaseOrder))
            {
                return new global::LightSwitchApplication.Implementation.PurchaseOrder();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ShippingMethod))
            {
                return new global::LightSwitchApplication.Implementation.ShippingMethod();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.StockCheckDetail))
            {
                return new global::LightSwitchApplication.Implementation.StockCheckDetail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.StockCheck))
            {
                return new global::LightSwitchApplication.Implementation.StockCheck();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Supplier))
            {
                return new global::LightSwitchApplication.Implementation.Supplier();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Customer) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Customer);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.OrderDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.OrderDetail);
            }
            if (typeof(global::LightSwitchApplication.Order) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Order);
            }
            if (typeof(global::LightSwitchApplication.ProductCategory) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProductCategory);
            }
            if (typeof(global::LightSwitchApplication.Product) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Product);
            }
            if (typeof(global::LightSwitchApplication.ProductSubscriber) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProductSubscriber);
            }
            if (typeof(global::LightSwitchApplication.PurchaseOrderDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.PurchaseOrderDetail);
            }
            if (typeof(global::LightSwitchApplication.PurchaseOrder) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.PurchaseOrder);
            }
            if (typeof(global::LightSwitchApplication.ShippingMethod) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ShippingMethod);
            }
            if (typeof(global::LightSwitchApplication.StockCheckDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.StockCheckDetail);
            }
            if (typeof(global::LightSwitchApplication.StockCheck) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.StockCheck);
            }
            if (typeof(global::LightSwitchApplication.Supplier) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Supplier);
            }
            return null;
        }
    }
}
